sudo: required
group: deprecated-2017Q2
language: bash
branches:
  only:
    - master
services:
  - docker
before_install:
  - docker info
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
install:
  - docker build --build-arg VCS_REF=$TRAVIS_COMMIT --build-arg BUILD_DATE=$(date +"%Y-%m-%dT%H:%M:%SZ") --build-arg VERSION=$VERSION -t $DOCKER_REPO:$VERSION-$TARGET-$DIST $VERSION/$TARGET/$DIST
  - docker run --rm --tty $DOCKER_REPO:$VERSION-$TARGET-$DIST uname -a
after_success:
  - docker login -e=$DOCKER_EMAIL -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
  - docker push $DOCKER_REPO:$VERSION-$TARGET-$DIST
env:
  #global:
  # -  DOCKER_REPO=openhab/openhab
  # Encrypted:
  # -  DOCKER_EMAIL
  # -  DOCKER_USERNAME
  # -  DOCKER_PASSWORD
  matrix:
    - DIST=debian TARGET=amd64 VERSION=1.8.3
    - DIST=debian TARGET=armhf VERSION=1.8.3
    - DIST=debian TARGET=arm64 VERSION=1.8.3
    - DIST=debian TARGET=amd64 VERSION=2.0.0
    - DIST=debian TARGET=armhf VERSION=2.0.0
    - DIST=debian TARGET=arm64 VERSION=2.0.0
    - DIST=debian TARGET=amd64 VERSION=2.1.0
    - DIST=debian TARGET=armhf VERSION=2.1.0
    - DIST=debian TARGET=arm64 VERSION=2.1.0
    - DIST=debian TARGET=amd64 VERSION=2.2.0
    - DIST=debian TARGET=armhf VERSION=2.2.0
    - DIST=debian TARGET=arm64 VERSION=2.2.0
    - DIST=debian TARGET=amd64 VERSION=2.3.0
    - DIST=debian TARGET=armhf VERSION=2.3.0
    - DIST=debian TARGET=arm64 VERSION=2.3.0
    - DIST=debian TARGET=amd64 VERSION=2.4.0-snapshot
    - DIST=debian TARGET=armhf VERSION=2.4.0-snapshot
    - DIST=debian TARGET=arm64 VERSION=2.4.0-snapshot
    - DIST=alpine TARGET=amd64 VERSION=1.8.3
    - DIST=alpine TARGET=armhf VERSION=1.8.3
    - DIST=alpine TARGET=arm64 VERSION=1.8.3
    - DIST=alpine TARGET=amd64 VERSION=2.0.0
    - DIST=alpine TARGET=armhf VERSION=2.0.0
    - DIST=alpine TARGET=arm64 VERSION=2.0.0
    - DIST=alpine TARGET=amd64 VERSION=2.1.0
    - DIST=alpine TARGET=armhf VERSION=2.1.0
    - DIST=alpine TARGET=arm64 VERSION=2.1.0
    - DIST=alpine TARGET=amd64 VERSION=2.2.0
    - DIST=alpine TARGET=armhf VERSION=2.2.0
    - DIST=alpine TARGET=arm64 VERSION=2.2.0
    - DIST=alpine TARGET=amd64 VERSION=2.3.0
    - DIST=alpine TARGET=armhf VERSION=2.3.0
    - DIST=alpine TARGET=arm64 VERSION=2.3.0
    - DIST=alpine TARGET=amd64 VERSION=2.4.0-snapshot
    - DIST=alpine TARGET=armhf VERSION=2.4.0-snapshot
    - DIST=alpine TARGET=arm64 VERSION=2.4.0-snapshot
matrix:
  fast_finish: true
