sudo: required
language: bash
branches:
  only:
    - master
services:
  - docker
before_install:
  - docker info
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
install:
  - docker build --build-arg VCS_REF=$TRAVIS_COMMIT --build-arg BUILD_DATE=$(date +"%Y-%m-%dT%H:%M:%SZ") -t $DOCKER_REPO:$VERSION-$TARGET $VERSION/$TARGET
  - docker run --rm $DOCKER_REPO:$VERSION-$TARGET uname -a
after_success:
  - docker login -e=$DOCKER_EMAIL -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
  - docker push $DOCKER_REPO:$VERSION-$TARGET
env:
  #global:
  # -  DOCKER_REPO=openhab/openhab
  # Encrypted:
  # -  DOCKER_EMAIL
  # -  DOCKER_USERNAME
  # -  DOCKER_PASSWORD
  matrix:
    - TARGET=amd64 VERSION=1.8.3
    - TARGET=armhf VERSION=1.8.3
    - TARGET=arm64 VERSION=1.8.3
    - TARGET=amd64 VERSION=2.0.0
    - TARGET=armhf VERSION=2.0.0
    - TARGET=arm64 VERSION=2.0.0
    - TARGET=amd64 VERSION=2.1.0-snapshot
    - TARGET=armhf VERSION=2.1.0-snapshot
    - TARGET=arm64 VERSION=2.1.0-snapshot
matrix:
  fast_finish: true

